# Real bimanual UR3 with two GELLO leaders.
robot: bi_ur3
mode: real
left_robot_ip: 158.132.172.193
right_robot_ip: 158.132.172.214
left_teleop_port: /dev/ttyUSB0
right_teleop_port: /dev/ttyUSB1

repo_id: USER/BI_UR3_DATASET1
single_task: Describe the bimanual task here.
num_episodes: 10
episode_time_s: 60.0
display-data: false
max-joint-delta: 0.05

cameras:
  d415A:
    type: realsense
    serial_number_or_name: "839112062492"
    width: 640
    height: 480
    fps: 15
    use_depth: true
  
  d435I:
    type: realsense
    serial_number_or_name: "141222073387"
    width: 640
    height: 480
    fps: 15
    use_depth: true

  d415B:
    type: realsense
    serial_number_or_name: "830612060457"
    width: 640
    height: 480
    fps: 15
    use_depth: true
